name: Sandra Anna Sobanska, ThriveFul
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-coffeescript
  - jekyll-watch
  - jekyll-assets
  - jekyll-seo-tag
 # This will require each of these gems automatically.
 

